title: Ultimate Raylib C/C++ setup guide
email: steelphoenix2137@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  How to get Raylib working under your OS and with your preferred build system!
baseurl: "/raylib-setup" # the subpath of your site, e.g. /blog
url: "https://steelph0enix.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: steel_ph0enix
github_username: SteelPh0enix

theme: jekyll-theme-hacker